name: Deploy Nuxt 3
on:
  push:
    branches: ["konsinyasi", "main"]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Create .env for build
        run: |
          cat > .env << 'EOF'
          PORT=${{ secrets.PORT }}
          NUXT_API_URL=${{ secrets.NUXT_API_URL }}
          NUXT_API_BASE=${{ secrets.NUXT_API_BASE }}

          NUXT_OPENID_CONNECT_OP_ISSUER=${{ secrets.NUXT_OPENID_CONNECT_OP_ISSUER }}
          NUXT_OPENID_CONNECT_OP_CLIENT_ID=${{ secrets.NUXT_OPENID_CONNECT_OP_CLIENT_ID }}
          NUXT_OPENID_CONNECT_OP_CLIENT_SECRET=${{ secrets.NUXT_OPENID_CONNECT_OP_CLIENT_SECRET }}
          NUXT_OPENID_CONNECT_OP_CALLBACK_URL=${{ secrets.NUXT_OPENID_CONNECT_OP_CALLBACK_URL }}
          NUXT_OPENID_CONNECT_OP_POST_LOGOUT_REDIRECT_URI=${{ secrets.NUXT_OPENID_CONNECT_OP_POST_LOGOUT_REDIRECT_URI }}
          EOF

      - name: Install dependencies
        run: npm i

      - name: Build Nuxt 3
        run: npm run build

      - name: Tar build output
        run: tar -czf output.tar.gz .output

      - name: Upload build file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "output.tar.gz"
          target: ${{ secrets.APP_DIR }}

      - name: Extract and restart PM2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.APP_DIR }}

            echo "📌 Backup output lama"
            [ -d ".output" ] && mv .output .output-backup-$(date +%s)

            echo "🧹 Hapus semua backup kecuali yang terbaru"
            ls -dt .output-backup-* 2>/dev/null | tail -n +2 | xargs rm -rf || true

            echo "📌 Extract build baru"
            tar -xzf output.tar.gz

            echo "📌 Hapus file tar"
            rm -f output.tar.gz

            echo "🔄 Load NVM"
            source ~/.nvm/nvm.sh

            echo "🔄 Restart PM2" 
            pm2 restart "trums-fe_8008" --update-env
